### ISSUE TITLE
Non-terminating execution from fresh install of LeR

### ISSUE THREAD

**Issue by enricoteofilo** [hemantaph/ler#9]
I've followed the lines from the documentation to install LeR in a dedicated new conda environment:
```
git clone https://github.com/hemantaph/ler.git
cd ler
conda env create -f ler.yml
conda activate ler
pip install -e .
```
I get a non-terminating code execution by trying to compute the following simple lines with `python strong.py` terminal command:
```
import numpy as np
import multiprocessing as mp
import time
import corner
from astropy.cosmology import FlatLambdaCDM
from ler.gw_source_population import CBCSourceParameterDistribution
from ler.rates import LeR

BBH_SAMPLE_SIZE = 10
BATCH_SIZE = 5
DEBUG = True
cosmo = FlatLambdaCDM(H0=70, Om0=0.3)
if DEBUG: print('cosmo done')
ler = LeR()
if DEBUG: print('printing LeR models and parameters done')
print('JOB TERMINATED!')
```
Example of code execution (interrupted manually):
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/enrico.teofilo/Gitfiles/gwcl/strong.py", line 38, in <module>
    ler = LeR()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/rates/ler.py", line 472, in __init__
    initialization()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/rates/ler.py", line 455, in initialization
    self.class_initialization(params=kwargs)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/rates/ler.py", line 738, in class_initialization
    LensGalaxyParameterDistribution.__init__(
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/lens_galaxy_parameter_distribution.py", line 272, in __init__
    self.class_initialization_lens(params=kwargs);
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/lens_galaxy_parameter_distribution.py", line 348, in class_initialization_lens
    OpticalDepth.__init__(
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/optical_depth.py", line 222, in __init__
    self.initialize_optical_depth_function(tau_name, vd_name);
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/optical_depth.py", line 352, in initialize_optical_depth_function
    optical_depth_setter = interpolator_from_pickle(
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/utils/utils.py", line 654, in interpolator_from_pickle
    y = pdf_func(x)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/optical_depth.py", line 725, in optical_depth_multiprocessing
    with Pool(processes=self.npool) as pool:
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/enrico.teofilo/Gitfiles/gwcl/strong.py", line 38, in <module>
    ler = LeR()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/rates/ler.py", line 472, in __init__
    initialization()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/rates/ler.py", line 455, in initialization
    self.class_initialization(params=kwargs)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/rates/ler.py", line 738, in class_initialization
    LensGalaxyParameterDistribution.__init__(
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/lens_galaxy_parameter_distribution.py", line 272, in __init__
    self.class_initialization_lens(params=kwargs);
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/lens_galaxy_parameter_distribution.py", line 348, in class_initialization_lens
    OpticalDepth.__init__(
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/optical_depth.py", line 222, in __init__
    self.initialize_optical_depth_function(tau_name, vd_name);
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/optical_depth.py", line 352, in initialize_optical_depth_function
    optical_depth_setter = interpolator_from_pickle(
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/utils/utils.py", line 654, in interpolator_from_pickle
    y = pdf_func(x)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/optical_depth.py", line 725, in optical_depth_multiprocessing
    with Pool(processes=self.npool) as pool:
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/enrico.teofilo/Gitfiles/gwcl/strong.py", line 38, in <module>
    ler = LeR()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/rates/ler.py", line 472, in __init__
    initialization()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/rates/ler.py", line 455, in initialization
    self.class_initialization(params=kwargs)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/rates/ler.py", line 738, in class_initialization
    LensGalaxyParameterDistribution.__init__(
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/lens_galaxy_parameter_distribution.py", line 272, in __init__
    self.class_initialization_lens(params=kwargs);
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/lens_galaxy_parameter_distribution.py", line 348, in class_initialization_lens
    OpticalDepth.__init__(
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/optical_depth.py", line 222, in __init__
    self.initialize_optical_depth_function(tau_name, vd_name);
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/optical_depth.py", line 352, in initialize_optical_depth_function
    optical_depth_setter = interpolator_from_pickle(
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/utils/utils.py", line 654, in interpolator_from_pickle
    y = pdf_func(x)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/optical_depth.py", line 725, in optical_depth_multiprocessing
    with Pool(processes=self.npool) as pool:
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/enrico.teofilo/Gitfiles/gwcl/strong.py", line 38, in <module>
    ler = LeR()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/rates/ler.py", line 472, in __init__
    initialization()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/rates/ler.py", line 455, in initialization
    self.class_initialization(params=kwargs)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/rates/ler.py", line 738, in class_initialization
    LensGalaxyParameterDistribution.__init__(
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/lens_galaxy_parameter_distribution.py", line 272, in __init__
    self.class_initialization_lens(params=kwargs);
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/lens_galaxy_parameter_distribution.py", line 348, in class_initialization_lens
    OpticalDepth.__init__(
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/optical_depth.py", line 222, in __init__
    self.initialize_optical_depth_function(tau_name, vd_name);
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/optical_depth.py", line 352, in initialize_optical_depth_function
    optical_depth_setter = interpolator_from_pickle(
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/utils/utils.py", line 654, in interpolator_from_pickle
    y = pdf_func(x)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/site-packages/ler/lens_galaxy_population/optical_depth.py", line 725, in optical_depth_multiprocessing
    with Pool(processes=self.npool) as pool:
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/enrico.teofilo/anaconda3/envs/ler/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

I've also tried cloning the `igwn` conda environment from the LIGO Grid and installing ler both with `pip install ler` and the other following lines:
```
git clone https://github.com/hemantaph/ler.git
cd ler
conda env update --file ler.yml
pip install -e .
```
Same non-terminating execution no matter how I install LeR. What am I doing wrong?
Let me know if additional details are needed.

**Comment by hemantaph** [comment]
Thanks for pointing it out. It has been working if you follow this [example](https://github.com/hemantaph/ler/blob/main/examples/rates/LeR_short_example.py). But I have modified the code to work either way. The problem was in the multiprocessor settings. I have made these changes in ['ler/\_\_init\_\_.py' file](https://github.com/hemantaph/ler/blob/facaeb9b03bd1873509ac8c9128369d5775d4a15/ler/__init__.py#L13).

```
def set_multiprocessing_start_method():
    if os.name == 'posix':  # posix indicates the program is run on Unix/Linux/Mac
      print("Setting multiprocessing start method to 'fork'")
      try:
         mp.set_start_method('fork', force=True)
      except RuntimeError:
         # The start method can only be set once and must be set before any process starts
         pass
    else:
      print("Setting multiprocessing start method to 'spawn'")
      # For Windows and other operating systems, use 'spawn'
      try:
         mp.set_start_method('spawn', force=True)
      except RuntimeError:
         pass
```

**Comment by enricoteofilo** [comment]
> Thanks for pointing it out. It has been working if you follow this [example](https://github.com/hemantaph/ler/blob/main/examples/rates/LeR_short_example.py). But I have modified the code to work either way. The problem was in the multiprocessor settings. I have made these changes in ['ler/__init__.py' file](https://github.com/hemantaph/ler/blob/facaeb9b03bd1873509ac8c9128369d5775d4a15/ler/__init__.py#L13).
> 
> ```
> def set_multiprocessing_start_method():
>     if os.name == 'posix':  # posix indicates the program is run on Unix/Linux/Mac
>       print("Setting multiprocessing start method to 'fork'")
>       try:
>          mp.set_start_method('fork', force=True)
>       except RuntimeError:
>          # The start method can only be set once and must be set before any process starts
>          pass
>     else:
>       print("Setting multiprocessing start method to 'spawn'")
>       # For Windows and other operating systems, use 'spawn'
>       try:
>          mp.set_start_method('spawn', force=True)
>       except RuntimeError:
>          pass
> ```

Thank you! Maybe it would be a good idea to specify the need for a `main` in the documentation.

**Comment by hemantaph** [comment]
I have added related information in the documentation to avoid users running into this problem; [link](https://ler.readthedocs.io/en/latest/Installation2.html#installation).

**Comment by enricoteofilo** [comment]
Thank you!
